

services:
    dns:
      build:
        context: ./dns
        dockerfile: Dockerfile
      container_name: dns
      ports:
        -  "54:54/tcp"
        -  "53:53/udp"
    
    asa-server:
      build:
        context: ./asa-server
        dockerfile: Dockerfile
      container_name: asa-server
      networks:
        - asa-network
    
    asa-server2:
      build: 
        context: ./asa-server
        dockerfile: Dockerfile
      container_name: asa-server2
      networks:
        - asa-network

    home:
      build:
        context: ./web
        dockerfile: Dockerfile
      container_name: home
      networks:
        - asa-network

    proxy:
      build:
        context: ./proxy
        dockerfile: Dockerfile
      container_name: proxy-nginx
      ports:
        - 80:80/tcp
      depends_on:
        - asa-server
      networks:
        - asa-network

networks:
  asa-network:
    driver: bridge
